package org.calevin.navaja.util;

public class NavajaConstantes {

    public static final String AL_INVOCAR_METODO = "al invocar metodo";	  
    public static final String ATRIBUTO = "atributo";
    public static final String CARPETA_DE_CONF = "carpeta de configuración";
    public static final String CAMPO = "campo";
    public static final String CLASE = "clase";
    public static final String COMILLA = "\"";
    public static final String COMA = ",";    
    public static final String CON = "con";
    public static final String CONEXION = "conexion";     
    public static final String DE = "de";    
    public static final String DEFINIDA = "definida";
    public static final String DEFINIDO  = "definido";   
    public static final String DEFINIDA_DOS_VECES = "definida dos veces";    
    public static final String DEFINIDO_DOS_VECES = "definido dos veces";
    public static final String DESCONOCIDO = "desconocido";    
    public static final String EN = "en";
    public static final String EN_EL_MAPEO = "en el mapeo";
    public static final String EL = "el";    
    public static final String ERROR = "error";    
    public static final String ES = "es";
    public static final String ESPACIO = " ";
    public static final String EXISTE = "existe";
    public static final String GET = "get";     
    public static final String INSTANCIA = "instancia";    
    public static final String INVALIDA = "invalida";
    public static final String INVALIDO = "invalido";
    public static final String NO = "no";
    public static final String NOMBRE = "nombre";
    public static final String NULA = "nula";
    public static final String NULO = "nulo";
    public static final String LA = "la";
    public static final String O = "o";
    public static final String PUNTO = ".";
    public static final String SET = "set";   
    public static final String SOPORTADA = "soportada";
    public static final String SOPORTADO = "soportado";
    public static final String SQL = "SQL";    
    public static final String TABLA = "tabla";
    public static final String VACIA = "vacia";
    public static final String VACIO = "vacio";
    public static final String VALOR = "valor";    
    public static final String TIPO = "tipo";
    
    //COMPUESTAS
    public static final String ESPACIO_COMILLA = ESPACIO + COMILLA;
    public static final String COMILLA_ESPACIO = COMILLA + ESPACIO;
    public static final String COMA_ESPACIO = COMA + ESPACIO;    
    public static final String NO_EXISTE = NO + ESPACIO + EXISTE;
    public static final String NO_DEFINIDA = NO + DEFINIDA;
    public static final String NO_DEFINIDO = NO + DEFINIDO;    
    public static final String NO_SOPORTADA = NO + ESPACIO + SOPORTADA;
    public static final String NO_SOPORTADO = NO + ESPACIO + SOPORTADO;
    public static final String INVALIDA_O_NO_SOPORTADA = INVALIDA + ESPACIO + O + NO_SOPORTADA;
    public static final String INVALIDO_O_NO_SOPORTADO = INVALIDO + ESPACIO + O + NO_SOPORTADO;
    public static final String VACIA_O_INVALIDA = VACIA + ESPACIO + O + ESPACIO + INVALIDA;
    public static final String VACIA_O_INVALIDO = VACIA + ESPACIO + O + ESPACIO + INVALIDO;
    public static final String VACIA_O_NULA = VACIA + ESPACIO + O + ESPACIO + NULA;
    public static final String VACIO_O_NULO = VACIO + ESPACIO + O + ESPACIO + NULO;
    public static final String GUION_BAJO_OR_PUNTO_XML = "_or.xml";
    public static final String TIPO_SQL = TIPO + ESPACIO + SQL;
    public static final String TIPO_DESCONOCIDO = TIPO + ESPACIO + DESCONOCIDO;
    public static final String PUNTO_ESPACIO = PUNTO + ESPACIO;
    public static final String CONEXION_NULA = LA + CONEXION + ESPACIO + ES + ESPACIO +  NULA;    
    public static final String CONEXION_INVALIDA = LA + CONEXION + ESPACIO + ES + ESPACIO + INVALIDA;
    public static final String ATRIBUTO_NULO = EL + ESPACIO + ATRIBUTO + ESPACIO + ES + ESPACIO + NULO;
    public static final String INSTANCIA_NULA = LA + ESPACIO + INSTANCIA + ESPACIO + ES + ESPACIO + NULA;        
}
